#!/bin/bash

AFL_TOKEN_FILE="/tmp_dir/temp_output.txt"
LD_PRELOAD="/AFLplusplus/utils/libtokencap/libtokencap.so"
target_bin="/path/to/target/bin"
target_output="/path/to/output"
timeout_sec="3"
args_list="$PWD/args_list.list"

touch $AFL_TOKEN_FILE
get_opt(){
${target_bin} --help | egrep "-" | awk '{print $1}' | egrep '-' | sort -u | egrep '-' > ${args_list}
}
#get_opt

function with_opt(){
args=($(cat $args_list | tr "," "\n"));
	for each_arg in "${args[@]}"; do
	for seed in $(find ${target_output} -type f -name "id*"); 
	do ${LD_PRELOAD} \
	timeout -s SIGKILL ${timeout_sec} \
	${target_bin} \
	${each_arg} \
	${seed} ;
	echo current flag: ${each_arg};
done
done
}
#with_opt

function no_opt(){
	for seed in $(find ${target_output} -type f -name "id*"); 
	do ${LD_PRELOAD} \
	timeout -s SIGKILL ${timeout_sec} \
	${target_bin} \
	${seed} ;
done
}
no_opt

function get_sort(){
cat ${AFL_TOKEN_FILE} | sed 's/$/\"/g' | sed 's/^/\"/g' | sort -r -S 90% -u > ${AFL_TOKEN_FILE}.1
sed 's/""/"/g' ${AFL_TOKEN_FILE}.1 > ${AFL_TOKEN_FILE}.2; nl -s "_token=" ${AFL_TOKEN_FILE}.2 > $(basename ${target_bin})_${EPOCHSECONDS}_autogenerated.dict
}
get_sort
